---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: sandbox
  name:      lkebot
data:
  LKEBOT_SWEEP_INTERVAL: "5"
  LKEBOT_CHANNEL:        "botspam"

  LKEBOT_MAX_NODES:      "6"
  LKEBOT_MAX_CLUSTERS:   "4"

  LKEBOT_DEFAULT_REFION:      "us-east"
  LKEBOT_DEFAULT_INSTANCE:    "g6-standard-2"
  LKEBOT_DEFAULT_SIZE:        "1"
  LKEBOT_DEFAULT_K8S_VERSION: "1.18"

  LKEBOT_BLACKLIST_CLUSTERS:  "prod production important"

---
apiVersion: v1
kind: Secret
metadata:
  namespace: sandbox
  name:      lkebot
stringData:
  LKEBOT_LINODE_TOKEN: foo............
  LKEBOT_SLACK_TOKEN:  bar............

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sandbox
  name:      lkebot
spec:
  selector:
    matchLabels:
      app: lkebot

  replicas: 1
  template:
    metadata:
      labels:
        app: lkebot

    spec:
      containers:
        - name: lkebot
          image: filefrog/lkebot:latest
          imagePullPolicy: Always

          envFrom:
            - configMapRef:
                name: lkebot
            - secretRef:
                name: lkebot
